schema:
  version: 1
  actions:
    download:
      definition:
        function: "Invoke-Download"
        args:
          -fileName
          -link
          -downloadFolder
      defaults:
        downloadFolder: "${TMP}"
    callExe:
      definition:
        function: "Invoke-InstallExe"
        args:
          -fileName
          -fileLocation
          -execArguments
      defaults:
        fileLocation: "${TMP}"

tasks:
  - name: "Rider"
    description: "Download and install Rider IDE"
    actions:
      - cmd: download
        args:
          fileName: "install.exe"
          link: "https://download.jetbrains.com/rider/JetBrains.Rider-2024.3.4.exe"
      - cmd: callExe
        args:
          fileName: "install.exe"
          execArguments:
              - "/S"
              - "/CONFIG=${SETUP_PROJ}/src/rider/silent.config"
              - "/LOG=${TMP}/rider_install.log"
              - "/D=${IDES}/jetbrains/Rider"